### ISSUE TITLE
Improve navigation to make the site more useful for people.

### ISSUE THREAD

**Issue by jlengstorf** [apache/openwhisk-website#123]
## The Problem

As it stands, I think our navigation reads more like a press release than the nav for a site aimed at onboarding new people into the Apache OpenWhisk community.

We feature events and partners, but we don't actually reference documentation or getting started — that's all buried somewhere, and those links are to raw Markdown files located deep in a GitHub repo.

**We can do better.**

## Proposal: Let's Make It Better

After thinking about this from the perspective of someone who's just heard about Apache OpenWhisk and wants to check it out, I believe our nav should look more like this:

- Docs
- Get Started
- Community
- Resources

### What about all the content currently on the site?

I believe all of the existing content easily fits under the proposed nav structure as is.

- **About**, **Serverless**, and **FAQ** all fit in the "Docs" section.
- News (#54), **Events** (#99), Media, **Partners**, and Contact all live under "Community"
- Integrations (#104), Demos & Examples (#98), Use Cases (#105), Articles, and Tutorials (#53, #48) live under "Resources"
- Live Tutorial (#107), Sandbox (#108) live under "Get Started"

**NOTE:** The bolded items are what currently exists in the top-level nav. The other items either exist but are _not_ linked from the top nav, or _do not_ exist but have been proposed. Issues linked inline where applicable.

### What are the challenges of doing this?

This is going to be a significant undertaking, so we need to be clear on how much work is involved up front.

#### Compiling, editing, and moving content.

On the bright side, we have ~all~ most of this information already. Unfortunately, it's spread all over hell, and we don't expose it well _at all_.

- [ ] Collect all of the existing information
- [ ] Port existing data to this site
- [ ] Create missing content

#### Porting documentation.

This is likely going to be the biggest, ugliest task.

- [ ] Make sure the core team is comfortable hosting documentation on this site
- [ ] Figure out how to format the documentation within the site
- [ ] Port documentation from the GitHub repo to this site
- [ ] Create a process for editing the documentation (though this ought to be like anything else: submit a PR)

## Is This Worth It?

![Obviously](http://i.giphy.com/4zvt2G82JLXsQ.gif)

We have an open-source project here, and we rely _entirely_ on the community to keep the project alive. As it stands, our site looks cool. But the useful parts for a new potential community member are buried pretty deep, and the experience feels (and is) pretty janky and disjointed.

**We need to do better if we want to see the community grow.**

### Here's what successful open-source navigation looks like.

These sites are hugely successful, and almost all of them feature navigation that is _very_ similar to what's being proposed in this issue.

- [React.js](https://facebook.github.io/react/)
- [Swift](https://swift.org/)
- [Material Design Lite](https://getmdl.io/)
- [AngularJS](https://angularjs.org/)
- [npm](https://www.npmjs.com/)
- [Babel](https://babeljs.io/)

## Action Steps

Here's what we need to do in order to make this happen:

- [ ] Agree that the navigation needs fixin'.
- [ ] Agree on a better navigation structure.
- [ ] Assign content collector(s).
- [ ] Assign content creator(s).
- [ ] Get buy-in from the core team to port the docs.
- [ ] Design the docs.
- [ ] Port the docs.

Did I miss anything? Let's get this conversation underway and make Apache OpenWhisk one of the sites other open-source sites are jealous of.

**Comment by krook** [comment]
@jlengstorf @jthomas @nauerz-ibm @mrutkows 

@jlengstorf I assume what you mean by a problem with the docs is that we point directly to GitHub READMEs over on the main repo instead of hosting user friendly versions on this site? Rather than importing those materials into this site repo, what if for now we just create meta pages that then point to those pages (digesting the content if needed)? These meta pages, on openwhisk.org, would provide the context for the docs they are about to visit. This avoids having to pull the content over but it does add some short term duplication.

If in the future we do pull the openwhisk/openwhisk/docs here, that would be great, but let's break that longer term into a separate epic. The other thing that might of concern is that the Bluemix (or other provider) documentation rely directly on the content created over in that main docs area. As long as we don't style them when bringing them here, may not be an issue, but something to consider.

**Comment by jlengstorf** [comment]
@krook Sorry, I missed your reply previously.

> Rather than importing those materials into this site repo, what if for now we just create meta pages that then point to those pages (digesting the content if needed)?

I like this idea for some of the content (e.g. Docs), but most of it needs to live on-site.

Resources will effectively be a list of links anyways, so having a digest for a digest seems unwise. Community is really just an expanded contact page, so it's also more of a digest by nature.

**Getting Started is probably the biggest issue**, because it's going to be a medium-sized undertaking to create this, but I really think **it's critical to have an on-site "up and running in X minutes" kind of thing** — I feel like this is really Thing 1 for an open source project's primary site.

As a stop-gap, the docs _could_ be a top-level nav link that jumps to the GitHub docs. That's 1000% better than what we're doing right now. _However_, I'd love to see the docs ported to some kind of branded docs space soon — it's a small layer of polish that adds a huge amount of trust for new users because it implies that the project is mature enough to be usable in production. GitHub-only docs smack of alpha products and frequent breaking changes (at least in my experience).

The docs are already Markdown, so porting them as-is ought to be fairly straightforward. If we can get buy-in from the core committers to use the new docs location instead of working on the GitHub docs, it would have a fairly minimal impact on the workflow beyond updating everyone's upstream repo for documentation.

Another thing to consider as the project gains public traction is this: **the longer we leave temporary solutions in place, the harder it is to move to permanent solutions later.** External sites we don't control are going to start linking to resources, and if we break those links later (or require people to click twice to get to the "new" docs), we're adding one more hurdle between an interested party and the information they need to get started.

So while I don't think it's an emergency, I'd definitely place a high priority on choosing locations for things that are long-term viable and getting information moved there quickly. It's a headache now to avoid a nightmare later. :)

**Comment by krook** [comment]
@jlengstorf We've been adding quite a few more posts to Medium this month. How would you suggest we improve the social media icon visibility as mentioned in #146?

I assume we don't need to edit the icon SVGs to make larger sizes, but rather just scale the image tags? What's the best guidance? Seems like several approaches are available: https://css-tricks.com/scale-svg/

**Comment by jlengstorf** [comment]
@krook Those sizes are set in CSS, so you can manipulate them to whatever size you want. Be careful of going too large, though, or they'll look awful on smaller screens.

**Comment by jlengstorf** [comment]
@krook I played with the inspector to make sure I'm not misleading you. Make sure you target the social nav only. I'd add the following on about line 98 of [_site-nav.css](https://github.com/openwhisk/openwhisk.github.io/blob/master/_scss/block/_site-nav.scss):

``` scss
  &--social &__item {
    width: 40px; /* whatever width you want goes here */
  }
```

Gives you something like this:

![screencap by jlengstorf 39](https://cloud.githubusercontent.com/assets/163561/21947139/3d3c50b6-d9a9-11e6-864b-dff145580558.png)

**Comment by dgrove-oss** [comment]
closing as stale
